#!/usr/bin/env bash


function my_kill() {
    kill -9 $(ps -ef | grep "$1" | awk '{ print $2 }')
}

function admin_kill() {
    echo raspberry | sudo -kS kill -9 $(ps -ef | grep "$1" | awk '{ print $2 }')
}


echo kill connect
my_kill "[c]onnect_bridge"

echo kill pairing
my_kill "[p]air_headset"

echo admin kill 1
admin_kill "[h]eadset_bridge/headset"
echo admin kill 2
admin_kill "[r]fcomm connect"
echo admin kill 3
admin_kill "[s]udo -kS"
echo admin kill 4
admin_kill "[s]udo -kS"

